import http from "k6/http";
import { sleep } from "k6";
import { check, group } from "k6";
import { Counter } from "k6/metrics";

export let options = {
  scenarios: {
    my_web_test: {
      executor: 'per-vu-iterations',
      vus: 25,
      maxDuration: '5m',
      gracefulStop: '0s', // do not wait for iterations to finish in the end
      tags: { test_type: 'website' }, // extra tags for the metrics generated by this scenario
      exec: 'webtest', // the function this scenario will execute
    },
  },
  
  thresholds: {
    //http_req_failed: ['rate<0.01'],   // http errors should be less than 1% 
    'http_req_failed{test_type:website}': ['rate<0.01'],
    'http_req_duration{test_type:website}': ['p(90)<200'], // 99% of requests must complete below 200
  },
};

export function webtest() {

  group("login get cookie", function () {
    let response = http.get(`https://lab-load-testing.boardeffect.com/login`);

    const form = response.submitForm({
    formSelector: 'form',
    fields: { "login[login]": 'boardeffect', "login[password]": 'password1' },
    });

    console.log("login web form "+form.status)

    let jar = http.cookieJar();
    let cookies = jar.cookiesForURL(`https://lab-load-testing.boardeffect.com`);
    console.log(JSON.stringify(cookies));

    check(form, {
      'status': (r) => r.status === 200,
      'has session cookie': (r) => cookies._boardeffect_session !== undefined
    });

  });

  group("go to survey template", function () {
    const url = (`https://lab-load-testing.boardeffect.com/workrooms/8205/surveys?templates=1`);
    let response = http.get(url);
    console.log("go to survey template "+response.status)
    
    check(response, {
      "status 200": (r) => r.status === 200,
    });

  });

  group("open up survey template 2217", function () {
    // even though the link shows surveys it is actually getting the survey template id 
    const url = (`https://lab-load-testing.boardeffect.com/workrooms/8205/surveys/2217`);
    let response = http.get(url);
    console.log("open up survey template 2217 "+response.status)

    check(response, {
      "status 200": (r) => r.status === 200,
    });

  });


  group("download survey template file 37761", function () {
    // even though the link shows surveys it is actually downloading the survey template file 
    const url = (`https://lab-load-testing.boardeffect.com/downloads/vfile/37761`);
    let response = http.get(url);
    console.log("download survey template file 37761 "+response.status)

    check(response, {
      "status 200": (r) => r.status === 200,
    });

  });

}